#!/usr/bin/env python3
"""
MHPSS Nepal hub -- the side rail, generated and gated.

The website (root repository) navigates from a band across the top; the hub
navigates from a rail down the left. Two shapes for two things. The band is
generated by the root repository's tools/nav.py; this is the rail's half of
that file, kept in the hub repository because the hub owns its pages.

  check   exit non-zero if any page carries a rail the generator did not write
  apply   rewrite every <!--NAV:rail KEY--> block from the table below
"""
import os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# ------------------------------------------------------------------- the hub
RAIL = [
    ("group", "Dashboard", None),
    ("hubindex",    "Coordination view",   "./"),
    ("hubcoverage", "Coverage &amp; 4Ws",  "coverage.html"),
    ("hubinbox",    "Field inbox",         "inbox.html"),
    ("hubaccess",   "Access",              "access.html"),
    ("group", "Elsewhere", None),
    ("outforms",  "Field forms",   "../form/"),
    ("outpublic", "Public page",   "../"),
    ("outmethod", "Method",        "../method.html"),
]
# the sections of the coordination view itself, shown only on that page
HUBSECTIONS = [
    ("#coverage", "Coverage"), ("#who", "Who is doing what"), ("#when", "Over time"),
    ("#what", "Activities"),   ("#people", "Workforce"),      ("#helpline", "Helplines"),
    ("#layers", "Architecture"),
]

def rail_block(key):
    out = ['<aside class="rail" aria-label="Coordination hub">',
           '  <a class="railid" href="./">',
           '    <span data-mark="30"></span>',
           '    <span><b>MHPSS Nepal</b><i>Layer 2 &middot; coordination</i></span>',
           '  </a>',
           '  <nav>']
    for k, label, href in RAIL:
        if k == "group":
            out.append('    <span class="rgrp">%s</span>' % label)
            continue
        on = ' class="on" aria-current="page"' if k == key else ''
        out.append('    <a%s href="%s">%s</a>' % (on, href, label))
        if k == "hubindex" and key == "hubindex":
            out.append('    <span class="rsub">')
            for h, l in HUBSECTIONS:
                out.append('      <a href="%s">%s</a>' % (h, l))
            out.append('    </span>')
    out.append('  </nav>')
    # i18n.js mounts the language switch here. Without a slot it floats top
    # right, where on these pages it lands on top of the synthetic-data banner.
    out.append('  <span data-i18n-toggle class="railtoggle"></span>')
    out.append('  <p class="rfoot">Draft. Synthetic data only.</p>')
    out.append('</aside>')
    return "\n".join(out)

# ------------------------------------------------------------------- machinery
MARK = re.compile(r'<!--NAV:(rail) ([a-z0-9]+)-->.*?<!--/NAV-->', re.S)

def pages():
    found = []
    for dirpath, dirnames, filenames in os.walk(ROOT):
        dirnames[:] = [d for d in dirnames if d not in (".git", "tools", "node_modules", "data", "docs")]
        for fn in sorted(filenames):
            if not fn.endswith(".html"):
                continue
            p = os.path.join(dirpath, fn)
            s = open(p, encoding="utf-8").read()
            if MARK.search(s):
                found.append((os.path.relpath(p, ROOT), s))
    return found

def run(apply_it):
    rows, bad = [], 0
    for rel, s in pages():
        def sub(m):
            return '<!--NAV:rail %s-->\n%s\n<!--/NAV-->' % (m.group(2), rail_block(m.group(2)))
        new = MARK.sub(sub, s)
        key = MARK.search(s).group(2)
        same = (new == s)
        rows.append((rel, key, same))
        if not same:
            bad += 1
            if apply_it:
                open(os.path.join(ROOT, rel), "w", encoding="utf-8").write(new)
    print("MHPSS Nepal hub -- the rail")
    for rel, key, same in rows:
        print("  %-26s rail  %-12s %s" % (rel, key, "ok" if same else ("rewritten" if apply_it else "DIFFERS")))
    if not rows:
        print("\n  No page carries a rail marker. Nothing is generated, so nothing is")
        print("  guaranteed: add the markers or remove this gate.")
        return 1
    for k, label, href in RAIL:
        if k == "group" or k.startswith("out"):
            continue
        rel = "index.html" if href == "./" else href
        if not os.path.exists(os.path.join(ROOT, rel)):
            print("\n  INCOMPLETE -- the rail points at %s, which does not exist." % rel)
            return 1
    if apply_it:
        print("\n  %d page(s) rewritten from tools/rail.py." % bad)
        return 0
    if bad:
        print("\n  DRIFTED -- a page carries a rail the generator did not write.")
        print("  Edit tools/rail.py, then run: python3 tools/rail.py apply")
        return 1
    print("\n  True: every page's rail is the one written in tools/rail.py.")
    return 0

if __name__ == "__main__":
    sys.exit(run(len(sys.argv) > 1 and sys.argv[1] == "apply"))
