#!/usr/bin/env python3
"""
MHPSS Nepal hub -- the side rail, generated and gated.

The website (root repository) navigates from a band across the top; the hub
navigates from a rail down the left. Two shapes for two things. The band is
generated by the root repository's tools/nav.py; this is the rail's half of
that file, kept in the hub repository because the hub owns its pages.

  check   exit non-zero if any page carries a rail the generator did not write
  apply   rewrite every <!--NAV:rail KEY--> block from the table below
"""
import os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# ------------------------------------------------------------------- the hub
# The rail follows the structure of the Sadar Hati internal dashboard (read
# 17 Sep 2026, read-only): a brand block, then GROUPS that collapse and
# expand on a chevron, items inside them, and a footer. Two things added for
# this hub: the ARCHITECTURE STRIP at the very top -- the three layers, with
# the one the reader is standing in marked -- so nobody has to guess where
# they are; and the group state is remembered per browser.
#
# Restructured 17 Sep 2026 (evening). The GROUP headers are the main bar,
# the items under them the sub bar:
#   Coordination  -- the ONE dashboard page, index.html, whose sections are
#                    addressed by hash and switched from here. There is no
#                    separate "coordination view" any more: the synthetic
#                    page duplicated the dashboard and confused readers.
#   Field forms   -- not the forms (those are on the phones, layer 1) but
#                    each form's OUTPUT HOME in the hub: where the entries
#                    made on that form can be found. The Sadar Hati pattern
#                    ("Rumah Output"). One link opens the forms themselves.
#   Public site   -- one item, Home. The public pages navigate themselves.
#   Admin         -- at the bottom, and only drawn for an admin account
#                    (the rail script asks the bridge for the role). Rules
#                    protect the data either way; hiding it keeps the rail
#                    honest for everyone else.
GROUPS = [
    # (key, label, layer, em, items) -- items: (key, label, href)
    ("coord", "Coordination", "2", "layer 2", [
        ("hubindex",    "Dashboard &middot; overview", "./#overview"),
        ("hubwho",      "Who is where",                "./#who-is-where"),
        ("hubact",      "Activities",                  "./#activities"),
        ("hubreports",  "Reports received",            "./#reports"),
        ("hubpublish",  "Publish",                     "./#publish"),
    ]),
    ("forms", "Field forms", "1", "outputs", [
        ("outact",      "Activity report (5Ws)",  "./#reports"),
        ("outcontact",  "Service contact",        "forms.html#contact"),
        ("outref",      "Referral",               "forms.html#referral"),
        ("outphq",      "PHQ-9 follow-up",        "forms.html#phq9"),
        ("outself",     "Self-report",            "forms.html#selfreport"),
        ("outopen",     "Open the forms &rarr;",  "../form/"),
    ]),
    ("public", "Public site", "3", "layer 3", [
        ("outpublic",   "Home",                   "../"),
    ]),
    ("admin", "Admin", "2", "admin only", [
        ("hubaccess",   "Access &amp; sign-in",   "access.html"),
    ]),
]
# which group a PAGE stands in (its rail key is the page's, not an item's)
PAGE_GROUP = {"hubindex": "coord", "hubforms": "forms", "hubaccess": "admin"}
# the item lit when the page is opened without a hash
PAGE_DEFAULT = {"hubindex": "hubindex", "hubforms": "outcontact", "hubaccess": "hubaccess"}
# kept for the completeness check below: every hub page the rail points at
RAIL = [(k, l, h) for g in GROUPS for (k, l, h) in g[4]]

RAIL_JS = """(function(){
  var rail=document.currentScript.parentNode, KEY='mhpss-rail-groups';
  var saved={}; try{ saved=JSON.parse(localStorage.getItem(KEY)||'{}'); }catch(e){}
  rail.querySelectorAll('.rg').forEach(function(g){
    var k=g.getAttribute('data-g'), h=g.querySelector('.rgh');
    if(!g.classList.contains('here') && k in saved) g.classList.toggle('open', !!saved[k]);
    h.setAttribute('aria-expanded', g.classList.contains('open'));
    h.addEventListener('click', function(){
      g.classList.toggle('open'); var on=g.classList.contains('open');
      h.setAttribute('aria-expanded', on); saved[k]=on;
      try{ localStorage.setItem(KEY, JSON.stringify(saved)); }catch(e){}
    });
  });
  var m=rail.querySelector('.rmenu');
  if(m){ m.addEventListener('click', function(){
    var open=rail.classList.toggle('menu-open'); m.setAttribute('aria-expanded', open); }); }
  /* The lit item follows the address: a hub page's sections are hashes, and
     the same section can be reached from two groups (the activity report's
     output home IS the dashboard's Reports received), so every link that
     matches is lit, not just one. */
  function mark(){
    var path=location.pathname.split('/').pop()||'index.html', hash=location.hash||'';
    rail.querySelectorAll('.rgb > a').forEach(function(a){
      var href=a.getAttribute('href'); if(href.indexOf('../')===0) return;
      var file=href.split('#')[0], ah=href.indexOf('#')>=0 ? href.slice(href.indexOf('#')) : '';
      if(file==='./'||file==='') file='index.html';
      var on = file===path && (hash ? ah===hash : a.hasAttribute('data-default'));
      a.classList.toggle('on', on);
      if(on) a.setAttribute('aria-current','page'); else a.removeAttribute('aria-current');
    });
    if(rail.classList.contains('menu-open')){ rail.classList.remove('menu-open'); if(m) m.setAttribute('aria-expanded', false); }
  }
  window.addEventListener('hashchange', mark);
  document.addEventListener('DOMContentLoaded', mark);
  window.__railMark = mark;
  /* Admin is drawn only for an admin account. The bridge (assets/fb.js)
     loads after the rail, so the question is asked once the page is
     complete; a page without the bridge simply never shows it. */
  var adm=rail.querySelector('.rg.admin');
  if(adm){ document.addEventListener('DOMContentLoaded', function(){
    if(!(window.FB && window.FB.onStatus)) return;
    window.FB.onStatus(function(st){
      if(!(st && st.user && window.FB.myRole)){ adm.hidden=true; return; }
      window.FB.myRole().then(function(r){ adm.hidden = !(r && r.role==='admin'); }).catch(function(){ adm.hidden=true; });
    });
  }); }
})();"""

def rail_block(key):
    here_group = PAGE_GROUP.get(key)
    if here_group is None:
        for gk, glabel, layer, em, items in GROUPS:
            if any(k == key for k, _, _ in items):
                here_group = gk
    default = PAGE_DEFAULT.get(key, key)
    out = ['<aside class="rail" aria-label="Coordination hub">',
           '  <a class="railid" href="./">',
           '    <span data-mark="30"></span>',
           '    <span><b>MHPSS Nepal</b><i>Layer 2 &middot; coordination</i></span>',
           '  </a>',
           # -- the architecture strip: where the reader is, before anything else
           '  <div class="where" aria-label="Where you are in the system">',
           '    <span class="wlab">Architecture &middot; you are here</span>',
           '    <a class="lyr" href="../form/"><b>1</b><span>Field forms<i>on phones, works offline</i></span></a>',
           '    <a class="lyr on" href="./" aria-current="true"><b>2</b><span>Coordination<i>this hub &middot; restricted</i></span></a>',
           '    <a class="lyr" href="../"><b>3</b><span>Public site<i>published summaries only</i></span></a>',
           '  </div>',
           '  <button class="rmenu" type="button" aria-expanded="false"><span></span>Menu</button>',
           '  <nav>']
    for gk, glabel, layer, em, items in GROUPS:
        cls = "rg" + (" open here" if gk == here_group else (" open" if gk == "coord" else ""))
        if gk == "admin":
            cls += " admin"
        out.append('    <div class="%s" data-g="%s"%s>' % (cls, gk, " hidden" if gk == "admin" else ""))
        out.append('      <button class="rgh" type="button"><span class="dot l%s"></span>%s<em>%s</em><i class="chev"></i></button>' % (layer, glabel, em))
        out.append('      <div class="rgb">')
        for k, label, href in items:
            attrs = ''
            if k == default:
                attrs += ' class="on" aria-current="page" data-default'
            out.append('        <a%s href="%s">%s</a>' % (attrs, href, label))
        out.append('      </div>')
        out.append('    </div>')
    out.append('  </nav>')
    # i18n.js mounts the language switch here. Without a slot it floats top
    # right, where on these pages it lands on top of the status line.
    out.append('  <span data-i18n-toggle class="railtoggle"></span>')
    out.append('  <p class="rfoot">Draft. Figures are provisional.</p>')
    out.append('  <script>%s</script>' % RAIL_JS)
    out.append('</aside>')
    return "\n".join(out)

# ------------------------------------------------------------------- machinery
MARK = re.compile(r'<!--NAV:(rail) ([a-z0-9]+)-->.*?<!--/NAV-->', re.S)

def pages():
    found = []
    for dirpath, dirnames, filenames in os.walk(ROOT):
        dirnames[:] = [d for d in dirnames if d not in (".git", "tools", "node_modules", "data", "docs")]
        for fn in sorted(filenames):
            if not fn.endswith(".html"):
                continue
            p = os.path.join(dirpath, fn)
            s = open(p, encoding="utf-8").read()
            if MARK.search(s):
                found.append((os.path.relpath(p, ROOT), s))
    return found

def run(apply_it):
    rows, bad = [], 0
    for rel, s in pages():
        def sub(m):
            return '<!--NAV:rail %s-->\n%s\n<!--/NAV-->' % (m.group(2), rail_block(m.group(2)))
        new = MARK.sub(sub, s)
        key = MARK.search(s).group(2)
        same = (new == s)
        rows.append((rel, key, same))
        if not same:
            bad += 1
            if apply_it:
                open(os.path.join(ROOT, rel), "w", encoding="utf-8").write(new)
    print("MHPSS Nepal hub -- the rail")
    for rel, key, same in rows:
        print("  %-26s rail  %-12s %s" % (rel, key, "ok" if same else ("rewritten" if apply_it else "DIFFERS")))
    if not rows:
        print("\n  No page carries a rail marker. Nothing is generated, so nothing is")
        print("  guaranteed: add the markers or remove this gate.")
        return 1
    for k, label, href in RAIL:
        if href.startswith("../"):
            continue
        rel = href.split("#")[0]
        rel = "index.html" if rel in ("./", "") else rel
        if not os.path.exists(os.path.join(ROOT, rel)):
            print("\n  INCOMPLETE -- the rail points at %s, which does not exist." % rel)
            return 1
    if apply_it:
        print("\n  %d page(s) rewritten from tools/rail.py." % bad)
        return 0
    if bad:
        print("\n  DRIFTED -- a page carries a rail the generator did not write.")
        print("  Edit tools/rail.py, then run: python3 tools/rail.py apply")
        return 1
    print("\n  True: every page's rail is the one written in tools/rail.py.")
    return 0

if __name__ == "__main__":
    sys.exit(run(len(sys.argv) > 1 and sys.argv[1] == "apply"))
